var rr = {};
var r = [];

var db0 = db.getSiblingDB( "list_static" );
var col = db0.bank_swift_cn;
	col.find({}).forEach( function( doc ){
		if( !rr[ doc.city ] )
		{
			rr[ doc.city ] = 1;
			r.push( doc.city );
		}
	});
r = r.sort();

/*/
var r = ["AKSU","ANHUI","ANQING","ANSHAN","ANYANG","BAICHENG","BAISE","BAISHAN","BAODING","BAOJI","BAOTOU","BEIHAI","BEIJING","BENGBU","BENXI","BIJIE","BINZHOU","BOZHOU","CANGZHOU","CHANGCHUN","CHANGDE","CHANGJI","CHANGSHA","CHANGSHU","CHANGZHI","CHANGZHOU","CHAOYANG","CHAOZHOU","CHENGDE","CHENGDU","CHENZHOU","CHIFENG CITY","CHIZHOU","CHONGQING","CHUXIONG","CHUZHOU","CIXI","DALI","DALIAN","DANDONG","DANYANG","DAQING","DATONG","DAZHOU","DEQING","DEYANG","DEZHOU","DONG SHENG","DONGGUAN","DONGNING","DONGYING","DUYUN","ENSHI","ERLIANHAOTE","FANGCHENG","FANGCHENGGANG","FOSHAN","FUJIAN","FUQING","FUSHUN","FUXIN","FUYANG","FUZHOU","GANSU","GANZHOU","GUANGDONG","GUANGXI","GUANGZHOU","GUIGANG","GUILIN","GUIYANG","GUIZHOU","HAERBIN","HAIKOU","HAILAR","HAIMEN","HAINAN","HAINING","HAMI","HANDAN","HANGZHOU","HANKOU","HARBIN","HEBEI","HEFEI","HEGANG","HEIHE","HEILONGJIANG","HEKOU","HENAN","HENGSHUI","HENGYANG","HESHAN","HEYUAN","HEZE","HOHHOT","HONGHE","HUAI'AN","HUAIBEI","HUAIHUA","HUANGGANG","HUANGSHAN","HUANGSHI","HUBEI","HUHEHAOTE","HUIZHOU","HULUDAO","HULUNBEIR","HUN CHUN","HUNAN","HUOERGUOSI","HUZHOU","JIAMUSI","JIAN","JIANGMEN","JIANGSU","JIANGXI","JIANGYAN","JIANGYIN","JIAOJIANG","JIAOZUO","JIAXING","JIEYANG","JILIN","JIMEI","JINAN","JINGDEZHEN","JINGMEN","JINGZHOU","JINHUA","JINING","JINZHONG","JINZHOU","JIUJIANG","JIUQUAN","JIXI","KAIFENG","KAIPING","KASHI","KORLA","KUNMING","KUNSHAN","LAIWU","LANGFANG","LANZHOU","LESHAN","LHASA","LIANYUNGANG","LIAOCHENG","LIAONING","LIAOYANG","LINFEN","LINYI","LISHUI","LIUPANSHUI","LIUZHOU","LONGYAN","LOUDI","LUAN","LUOYANG","LUZHOU","LVLIANG","MA'ANSHAN","MAANSHAN","MANZHOULI","MAOMING","MEIZHOU","MENGZI","MIANYANG","MUDANJIANG","NANCHANG","NANCHONG","NANHAI","NANJING","NANNING","NANPING","NANTONG","NANYANG","NEIMENG","NINGBO","NINGDE","NINGXIA","ORDOS","PANJIN","PANZHIHUA","PING DING SHAN","PINGHU","PINGLIANG","PINGXIANG","PIZHOU","PUDONG","PUTIAN","PUYANG","QIANJIANG","QING TIAN","QINGDAO","QINGHAI","QINGYANG","QINGYUAN","QINHUANGDAO","QINZHOU","QIQIHAR","QUANZHOU","QUJING","QUZHOU","RIZHAO","RUGAO","SANMING","SANSHUI","SANXIA","SANYA","SHAANXI","SHANGHAI","SHANGHAI WAIGAOQIAO","SHANGQIU","SHANGRAO","SHANTOU","SHANXI","SHAOGUAN","SHAOXING","SHAOYANG","SHEKOU","SHENYANG","SHENZHEN","SHI SHI","SHIJIAZHUANG","SHIYAN","SHUANGYASHAN","SHUNDE","SHUOZHOU","SICHUAN","SONGYUAN","SUIFENHE","SUIHUA","SUIZHOU","SUQIAN","SUZHOU","TAI ZHOU","TAIAN","TAICANG","TAISHAN","TAIYUAN","TAIZHOU","TANGGU","TANGSHAN","TIANJIN","TIANSHUI","TONGLIAO","TONGLING","TONGXIANG","ULANHOT","ULANQAB","URUMQI","WEIFANG","WEIHAI","WEINAN","WENLING","WENZHOU","WUHAI","WUHAN","WUHU","WUJIANG","WULUMUQI","WUWEI","WUXI","WUZHOU","XIAMEN","XIAN","XIANGFAN","XIANGTAN","XIANGXI","XIANGYANG","XIANNING","XIANYANG","XIAOGAN","XIAOSHAN","XILINGOL","XILINHOT","XINGHUA","XINGTAI","XINHUI","XINING","XINJIANG","XINXIANG","XINYANG","XINYU","XINZHOU","XUANCHENG","XUCHANG","XUZHOU","YAN CHENG","YAN'AN","YANBIAN","YANG PU","YANGJIANG","YANGQUAN","YANGZHOU","YANJI","YANTAI","YIBIN","YICHANG","YICHUN","YINCHUAN","YINGKOU","YINING","YIWU","YIXING","YIYANG","YONGKANG","YONGZHOU","YUEYANG","YULIN","YUNCHENG","YUNNAN","YUXI","YUYAO","ZAOZHUANG","ZHANGJIAGANG","ZHANGJIAJIE","ZHANGJIAKOU","ZHANGZHOU","ZHANJIANG","ZHAOQING","ZHENGZHOU","ZHENJIANG","ZHONGSHAN","ZHOUKOU","ZHOUSHAN","ZHUHAI","ZHUJI","ZHUZHOU","ZIBO","ZIGONG","ZUNYI"];
var r0 = {};
var i=0, iLen=r.length;
for( ; i<iLen; ++i ) r0[ r[ i ] ] = [];


var db0 = db.getSiblingDB( "list_static" );
var col = db0.bank_swift_cn;
col.find({}).forEach( function( doc ){
		//doc._id = NumberInt( r0[ doc.city[ 0 ] ].length ) );
		r0[ doc.city ].push( doc );
	});
r0
/*/
var r = ["AKSU","ANHUI","ANQING","ANSHAN","ANYANG","BAICHENG","BAISE","BAISHAN","BAODING","BAOJI","BAOTOU","BEIHAI","BEIJING","BENGBU","BENXI","BIJIE","BINZHOU","BOZHOU","CANGZHOU","CHANGCHUN","CHANGDE","CHANGJI","CHANGSHA","CHANGSHU","CHANGZHI","CHANGZHOU","CHAOYANG","CHAOZHOU","CHENGDE","CHENGDU","CHENZHOU","CHIFENG CITY","CHIZHOU","CHONGQING","CHUXIONG","CHUZHOU","CIXI","DALI","DALIAN","DANDONG","DANYANG","DAQING","DATONG","DAZHOU","DEQING","DEYANG","DEZHOU","DONG SHENG","DONGGUAN","DONGNING","DONGYING","DUYUN","ENSHI","ERLIANHAOTE","FANGCHENG","FANGCHENGGANG","FOSHAN","FUJIAN","FUQING","FUSHUN","FUXIN","FUYANG","FUZHOU","GANSU","GANZHOU","GUANGDONG","GUANGXI","GUANGZHOU","GUIGANG","GUILIN","GUIYANG","GUIZHOU","HAERBIN","HAIKOU","HAILAR","HAIMEN","HAINAN","HAINING","HAMI","HANDAN","HANGZHOU","HANKOU","HARBIN","HEBEI","HEFEI","HEGANG","HEIHE","HEILONGJIANG","HEKOU","HENAN","HENGSHUI","HENGYANG","HESHAN","HEYUAN","HEZE","HOHHOT","HONGHE","HUAI'AN","HUAIBEI","HUAIHUA","HUANGGANG","HUANGSHAN","HUANGSHI","HUBEI","HUHEHAOTE","HUIZHOU","HULUDAO","HULUNBEIR","HUN CHUN","HUNAN","HUOERGUOSI","HUZHOU","JIAMUSI","JIAN","JIANGMEN","JIANGSU","JIANGXI","JIANGYAN","JIANGYIN","JIAOJIANG","JIAOZUO","JIAXING","JIEYANG","JILIN","JIMEI","JINAN","JINGDEZHEN","JINGMEN","JINGZHOU","JINHUA","JINING","JINZHONG","JINZHOU","JIUJIANG","JIUQUAN","JIXI","KAIFENG","KAIPING","KASHI","KORLA","KUNMING","KUNSHAN","LAIWU","LANGFANG","LANZHOU","LESHAN","LHASA","LIANYUNGANG","LIAOCHENG","LIAONING","LIAOYANG","LINFEN","LINYI","LISHUI","LIUPANSHUI","LIUZHOU","LONGYAN","LOUDI","LUAN","LUOYANG","LUZHOU","LVLIANG","MA'ANSHAN","MAANSHAN","MANZHOULI","MAOMING","MEIZHOU","MENGZI","MIANYANG","MUDANJIANG","NANCHANG","NANCHONG","NANHAI","NANJING","NANNING","NANPING","NANTONG","NANYANG","NEIMENG","NINGBO","NINGDE","NINGXIA","ORDOS","PANJIN","PANZHIHUA","PING DING SHAN","PINGHU","PINGLIANG","PINGXIANG","PIZHOU","PUDONG","PUTIAN","PUYANG","QIANJIANG","QING TIAN","QINGDAO","QINGHAI","QINGYANG","QINGYUAN","QINHUANGDAO","QINZHOU","QIQIHAR","QUANZHOU","QUJING","QUZHOU","RIZHAO","RUGAO","SANMING","SANSHUI","SANXIA","SANYA","SHAANXI","SHANGHAI","SHANGHAI WAIGAOQIAO","SHANGQIU","SHANGRAO","SHANTOU","SHANXI","SHAOGUAN","SHAOXING","SHAOYANG","SHEKOU","SHENYANG","SHENZHEN","SHI SHI","SHIJIAZHUANG","SHIYAN","SHUANGYASHAN","SHUNDE","SHUOZHOU","SICHUAN","SONGYUAN","SUIFENHE","SUIHUA","SUIZHOU","SUQIAN","SUZHOU","TAI ZHOU","TAIAN","TAICANG","TAISHAN","TAIYUAN","TAIZHOU","TANGGU","TANGSHAN","TIANJIN","TIANSHUI","TONGLIAO","TONGLING","TONGXIANG","ULANHOT","ULANQAB","URUMQI","WEIFANG","WEIHAI","WEINAN","WENLING","WENZHOU","WUHAI","WUHAN","WUHU","WUJIANG","WULUMUQI","WUWEI","WUXI","WUZHOU","XIAMEN","XIAN","XIANGFAN","XIANGTAN","XIANGXI","XIANGYANG","XIANNING","XIANYANG","XIAOGAN","XIAOSHAN","XILINGOL","XILINHOT","XINGHUA","XINGTAI","XINHUI","XINING","XINJIANG","XINXIANG","XINYANG","XINYU","XINZHOU","XUANCHENG","XUCHANG","XUZHOU","YAN CHENG","YAN'AN","YANBIAN","YANG PU","YANGJIANG","YANGQUAN","YANGZHOU","YANJI","YANTAI","YIBIN","YICHANG","YICHUN","YINCHUAN","YINGKOU","YINING","YIWU","YIXING","YIYANG","YONGKANG","YONGZHOU","YUEYANG","YULIN","YUNCHENG","YUNNAN","YUXI","YUYAO","ZAOZHUANG","ZHANGJIAGANG","ZHANGJIAJIE","ZHANGJIAKOU","ZHANGZHOU","ZHANJIANG","ZHAOQING","ZHENGZHOU","ZHENJIANG","ZHONGSHAN","ZHOUKOU","ZHOUSHAN","ZHUHAI","ZHUJI","ZHUZHOU","ZIBO","ZIGONG","ZUNYI"];
var r0 = {};
var i=0, iLen=r.length;
for( ; i<iLen; ++i ) r0[ r[ i ][ 0 ] ] = [];


var db0 = db.getSiblingDB( "list_static" );
var col = db0.bank_swift_cn;
col.find({}).forEach( function( doc ){
		//doc._id = NumberInt( r0[ doc.city[ 0 ] ].length ) );
		r0[ doc.city[ 0 ] ].push( doc );
	});
//r0;

var db1 = db.getSiblingDB( "list_static__bank_swift" );
var colNm = "bank_swift_cn__";
var io;
for( var s in r0 ){
	io = r0[ s ];
	var col = db1.getCollection( colNm + s );

	var a = io;
	var i=0, iLen=a.length;
	for( ; i<iLen; ++i ){
		col.insert( a[ i ] );
	}
}
//*/